### ISSUE TITLE
ENOENT: no such file or directory, scandir '....\monorepo\pages'

### ISSUE THREAD

**Issue by binary64** [vinissimus/next-translate#395] opened 2020-12-10 00:45 UTC
Hi my nextjs root is inside a monorepo as ./apps/web/ but I get this error on start:

`ENOENT: no such file or directory, scandir 'monorepo\pages'`

Is it possible to scan until you hit the first i18n.json or something along those lines, then you know the root where ./pages directory is to be expected

Thanks! Great project

**Comment by aralroca** [comment] 2020-12-10 09:05
@binary64 Would it be possible for you to do a reproducible example? 🙏  This would be a great help to us. 😊 

The [examples we have](https://github.com/vinissimus/next-translate/tree/1.0.0/examples) are already under monorepo and we haven't encountered this problem

**Comment by binary64** [comment] 2020-12-10 15:20
Here's how to replicate:

```
npx create-nx-workspace@next
```
choose Next.js & CSS

```
npm i next-translate
```

next.config.js:
```
const withNx = require('@nrwl/next/plugins/with-nx');
const nextTranslate = require('next-translate')

module.exports = withNx({
  ...nextTranslate({
    locales: ["en", "fr"],
  }),
});
```

/i18n.json:
```
{
  "locales": ["en", "fr"],
  "defaultLocale": "en",
  "pages": {
    "*": ["common"],
    "/": ["home"]
  }
}
```

result:
```
ENOENT: no such file or directory, scandir 'C:\p\_temp\testt\pages'
```

**Comment by dapuicon** [comment] 2020-12-14 16:21
Similar issue,

I am working in a Next app deployed with a custom server. It is configured as a monorepo using `lerna`. Next app is located in `apps/frontend` and a  *custom server* is in `apps/backend`.

In order to run the Next App from the *custom server* I had to configure the `dir` where the Next (app/frontend) app is located.

```js
const Env = require('@app/env');

const port = parseInt(process.env.PORT, 10) || 8000;
const dev = Env.NODE_ENV !== 'production';
const app = Next({
    dev,
    dir: Path.resolve(process.env.NEXT_APP_PATH || '.') # dir where app (frontend) is located
});
```

However there is not such a thing to configure with **next-translate**.
As a workarround I have modified `src\plugin\index.tsx` in order to add that option.

![imagen](https://user-images.githubusercontent.com/1841517/102105703-00573680-3e30-11eb-93d0-ae7ee744d692.png)

so, my `next.config.js` now looks like this:
```js
const nextTranslate = require('next-translate');

module.exports = nextTranslate({}, { appPath: process.env.NEXT_APP_PATH });
```

It is not an elegant solution, but maybe it helps.

**Comment by aralroca** [comment] 2020-12-15 16:32
Replacing `process.cwd()` to `__dirname`  it should work: https://stackoverflow.com/a/9874415/4467741

> `process.cwd()` returns the current working directory,
>
> i.e. the directory from which you invoked the node command.
>
> `__dirname` returns the directory name of the directory containing the JavaScript source code file

**Comment by aralroca** [comment] 2020-12-15 18:07
@binary64 Now this can be defined as follows:

```js
const withNx = require('@nrwl/next/plugins/with-nx');
const nextTranslate = require('next-translate')

module.exports = withNx(nextTranslate({ dir: __dirname })); 
```

Or simple using `process.env.NEXT_APP_PATH` env variable.

Changes: https://github.com/vinissimus/next-translate/pull/407/files#diff-21682b68ed82193995e01bd3585b2a596634ce8bb436f9cc0c3c9a39af8e2f40R7

Prerelease: [1.0.1-canary.2](https://github.com/vinissimus/next-translate/releases/tag/1.0.1-canary.2)

However, I have now come across another issue along withNx webpack loader...

![image](https://user-images.githubusercontent.com/13313058/102253924-44b60580-3f08-11eb-8427-eb47b47e7060.png)

Babel should have to be executed after the next-translate webpack loader, but it's executed it before for some reason I don't know... Maybe it's me who doesn't have any experience with NX and maybe I left something behind 😕

**Comment by aralroca** [comment] 2020-12-16 20:24
@binary64 can you confirm that [1.0.1-canary.3](https://github.com/vinissimus/next-translate/releases/tag/1.0.1-canary.3) prerelease is working for you? Thank you 🙏

**Comment by binary64** [comment] 2020-12-17 13:28
Hi! Thanks for the update,

Unfortunately I get a similar error:

```
yarn run v1.22.10
$ nx serve

> nx run web:serve 
ENOENT: no such file or directory, scandir 'C:\p\proj\monorepo\pages'
error Command failed with exit code 1.
```

It should be looking in C:\p\proj\monorepo\apps\web\src\pages

**Comment by aralroca** [comment] 2020-12-17 16:33
Ops! And are you setting `NEXT_TRANSLATE_PATH=./apps/web`? Or how?

**Comment by binary64** [comment] 2020-12-31 17:38
With `NEXT_TRANSLATE_PATH=./apps/web yarn run nx serve` I get:
```
> nx run web:serve 
info  - automatically enabled Fast Refresh for 1 custom loader
Warning: Built-in CSS support is being disabled due to custom CSS configuration being detected.
See here for more info: https://err.sh/next.js/built-in-css-disabled

info  - Using external babel configuration from C:\p\pab\monorepo\apps\web\.babelrc.js
error - ./pages/_app.tsx:137:8
Syntax error: Unterminated string constant

  135 |     if (typeof self !== 'undefined' &&
  136 |         // AMP / No-JS mode does not inject these helpers:
> 137 |         '$RefreshHelpers
      |         ^
  138 | // @ts-ignore
  139 |     export default __appWithI18n(__Page_Next_Translate__, {
  140 | // @ts-ignore
```

**Comment by aralroca** [comment] 2021-01-01 15:59
Ah ok @binary64, it looks the same issue that I reported on this comment https://github.com/vinissimus/next-translate/issues/395#issuecomment-745467162. I'm not sure why this happens... Babel should have to be executed after the next-translate webpack loader, but it's executed it before for some reason I don't know... I'm going to investigate. Thank you.

**Comment by creativej** [comment] 2021-01-05 06:25
Hi, we're also getting the same error. I believe there's a bug in the [templateWithHoc](https://github.com/vinissimus/next-translate/blob/master/src/plugin/templateWithHoc.ts) method because the code parsed into the method is valid but the output is not. 

Before:
```js
    // Legacy CSS implementations will `eval` browser code in a Node.js context
    // to extract CSS. For backwards compatibility, we need to check we're in a
    // browser context before continuing.
    if (typeof self !== 'undefined' &&
        // AMP / No-JS mode does not inject these helpers:
        '$RefreshHelpers$' in self) {
```

After: 
```js
    // Legacy CSS implementations will `eval` browser code in a Node.js context
    // to extract CSS. For backwards compatibility, we need to check we're in a
    // browser context before continuing.
    if (typeof self !== 'undefined' &&
        // AMP / No-JS mode does not inject these helpers:
        '$RefreshHelpers
// @ts-ignore
    export default __appWithI18n(__Page_Next_Translate__, {
```

Hope it helps. 🙏

**Comment by aralroca** [comment] 2021-01-29 15:44
we move it to 1.0.3 to avoid blocking 1.0.2

**Comment by gsambrotta** [comment] 2021-01-29 18:16
Hi guys, I have the same error but I'm not sure is caused by the same issues. I don't include `pages/` directory at all in my app!
I tried to reproduce the example posted here: https://github.com/vinissimus/next-translate/issues/395#issuecomment-742586737 and I don't have problem building or running `npm start`

My main question is:
A Nextjs app should be deploy on production with or without /page directory? 
For me make sense that is without since that is not compiled code. But maybe I'm missing something??

**Comment by gsambrotta** [comment] 2021-02-04 16:15
@aralroca I tried out my solution with 1.0.3-canary and it didn't change much.

My file tree:
```
i18n.js
.next
node_modules
package.json
public
```
My steps:
`npm run build`
`npm start`


Here i get the error:
`Error: ENOENT: no such file or directory, scandir '/home/gio/repos/test_v4/elliotforwater_v4/ewf_prod/pages'`

I still wonder if I should have `pages/` in my file tree in production.

**Comment by krystianjj** [comment] 2021-02-18 22:11
Hi, 
We write on documentation in point 12 about mono-repo (https://github.com/vinissimus/next-translate#12-how-to-use-next-translate-in-a-mono-repo) but this solution doesn't work with nx.dev 
I seeting up `NEXT_TRANSLATE_PATH` but it's doesn't work. I still have error 
`ENOENT: no such file or directory, scandir '/temp/NX/project/pages'`

**Comment by shelooks16** [comment] 2021-02-25 14:23
Hi @gsambrotta, @krystianjj 

As of `1.0.3`, usage with NX brings this error:

![err](https://user-images.githubusercontent.com/13313058/102253924-44b60580-3f08-11eb-8427-eb47b47e7060.png)

You will not be able to use it, unfortunately :(

Once PR #527 got merged, next-translate will become NX-compatible. 

To setup next-translate with NX, you have to:

(a) Either pass env variable `NEXT_TRANSLATE_PATH` every time you run nx commands:
```
 npx cross-env NEXT_TRANSLATE_PATH=apps/myAppName nx serve myAppName
``` 
(b) or create ` .local.env` file in the workspace root folder and define the var there:
```
// .local.env

NEXT_TRANSLATE_PATH=apps/myAppName
```
With (b) all nx command will automatically read env form `.local.env`. Running `nx serve myAppName` will just work.

**Comment by aralroca** [comment] 2021-02-25 17:10
I pre-released the fix that @shelooks16 did under 1.0.4-canary.2. If you confirm that it works well, then I'm going to release it!

**Comment by krystianjj** [comment] 2021-02-25 18:58
Hi @shelooks16, @aralroca 
I just tested next-translate@1.04-canary.2 with NX and I confirm, now everything working great :) 
Thank you 👍

**Comment by shelooks16** [comment] 2021-02-25 23:06
@aralroca Hello again!

After spending sometime ensuring new changes work OK under different conditions, PR #527 opened a new issue. 
Since now all singular quotes are replaced in the entire `modifiedCode`, there is a chance to end up with nested "" pair inside another "" pair.

For example, usage with styled JSX fails the build:

![sc](https://user-images.githubusercontent.com/33040081/109225647-37e64580-77c6-11eb-991a-35b03a031c72.jpg)

Instead of replacing all single qoutes, only special cases of the .replace() method to be considered:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#specifying_a_string_as_a_parameter

Original issue was caused by `'$RefreshHelpers$'`, and I believe this is the only thing that must be replaced.

I will submit a new PR with updated Regex.

**Comment by aralroca** [comment] 2021-03-04 14:32
@shelooks16 can I close this issue? It is finally resolved?

**Comment by shelooks16** [comment] 2021-03-04 15:05
@aralroca yeah, of course. Thanks.

From `1.0.5-canary.1` all goes smooth, not issues so far.

**Comment by sergeyshaykhullin** [comment] 2021-05-23 11:36
@aralroca Maybe i am doing something wrong but... I am getting same error

I have repo with single next js project, build structure:

```
.next
node_modules
public
i18n.json
next.config.js
package.json
```

npm start throws

```
npm : Error: ENOENT: no such file or directory, scandir 'REDACTED_PATH\pages'
At line:1 char:1
+ npm start
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error: ENOENT: ...\REDACTED_PATH\pages':String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
    at Object.readdirSync (node:fs:1381:3)
    at nextTranslate (REDACTED_PATH\node_modules\next-translate\lib\cjs\plugin\index.js:51:10)
    at REDACTED_PATH\node_modules\next-compose-plugins\lib\compose.js:100:23
    at Array.forEach (<anonymous>)
    at composePlugins (REDACTED_PATH\node_modules\next-compose-plugins\lib\compose.js:77:11)
    at REDACTED_PATH\node_modules\next-compose-plugins\lib\index.js:22:38
    at normalizeConfig (REDACTED_PATH\node_modules\next\dist\next-server\server\config-shared.js:1:1696)
    at loadConfig (REDACTED_PATH\node_modules\next\dist\next-server\server\config.js:8:136)
    at async NextServer.loadConfig (REDACTED_PATH\node_modules\next\dist\server\next.js:1:3155)
    at async NextServer.prepare (REDACTED_PATH\node_modules\next\dist\server\next.js:1:2679) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'REDACTED_PATH\\pages'
}
```

**But** if i add empty `pages` folder:

```
.next
node_modules
pages/{empty}
public
i18n.json
next.config.js
package.json
```

All is working fine: translations are working, application is not throwing any errors

**Comment by sergeyshaykhullin** [comment] 2021-05-23 15:54
The working configuration is:

1. Copy full `pages` folder to docker image
2. Use next-translate@1.0.1

None of other combinations is not working =(

**Comment by krystianjj** [comment] 2021-05-23 19:09
Hi @sergeyshaykhullin,
You have different problem...
Nextjs must have `pages` directory because nextjs have build in router. 
Check if you copy `pages` to correct main directory of project.

**Comment by sergeyshaykhullin** [comment] 2021-05-23 19:31
@krystianjj 

Hmm, in production i have a `.next` folder with compiled pages

I never copied source `pages` and next is running ok

**Comment by krystianjj** [comment] 2021-05-23 19:39
@sergeyshaykhullin if you use this Dockerfile configuration -> https://nextjs.org/docs/deployment you must add lines to copy i18n.js configuration to buid image if you have next-translate config in separare file.
`COPY --from=builder /app/i18n.js ./`

**Comment by sergeyshaykhullin** [comment] 2021-05-23 19:41
@krystianjj If you don't copy i18n.json you will get another error

This is my Dockerfile

```Dockerfile
FROM node:16-alpine as build
WORKDIR /app
COPY . .
RUN npm ci
RUN npm run build
RUN npm prune --production

FROM node:16-alpine
WORKDIR /app
COPY --from=build /app/public public
COPY --from=build /app/.next .next
COPY --from=build /app/next.config.js next.config.js
COPY --from=build /app/node_modules node_modules
COPY --from=build /app/package.json package.json
COPY --from=build /app/i18n.json i18n.json

# TODO: HACK https://github.com/vinissimus/next-translate/issues/395
COPY --from=build /app/src/pages src/pages

ENTRYPOINT ["npm", "start"]
```

**Comment by krystianjj** [comment] 2021-05-23 20:12
@sergeyshaykhullin your `Dockerfile` works on my project. 
I only change line `COPY --from=build /app/src/pages src/pages` to `COPY --from=build /app/pages ./pages`

**Comment by sergeyshaykhullin** [comment] 2021-05-23 20:17
Yes, this configuration is working

But you should not to copy your source pages

**Comment by krystianjj** [comment] 2021-05-23 21:16
@sergeyshaykhullin in my project when I comment line with `nextTranslate()` in next.config.js your Dockerfile working with comment copy `pages` directory.

**Comment by sergeyshaykhullin** [comment] 2021-05-23 21:48
> If i disable next-translate plugin next will start without errors and serve/render pages as normal

@krystianjj Yes, if you disable next-translate you can omit copying source pages and next will use .next/server/pages
But... It seems not that i want)

If you uncomment your `nextTranslate()` and do not copy original pages to `src/pages` or `pages` you will get an error

**Comment by mvierssen** [comment] 2021-06-08 02:46
I run into the same issue. The docker file as described here:

https://nextjs.org/docs/deployment

...cannot work because next-translate seems to want the source pages to be included inside the docker image unlike the example from the link above.

**Comment by aralroca** [comment] 2021-06-08 07:07
Ok I reopen it!

**Comment by sergeyshaykhullin** [comment] 2021-06-08 09:44
@mvierssen You can copy pages from .next folder as a temporary workaround, to not to copy source

I am using 1.0.1 version, it works fine with copied pages
1.0.7 is failing

**Comment by xerenahmed** [comment] 2021-06-08 09:48
This works for me
```Dockerfile
COPY --from=builder /app/.next/server/pages ./pages
```

basically you need copy pages from .next/server/pages to workdir. Idk why is needed.

**Comment by mvierssen** [comment] 2021-06-08 21:42
Thanks @sergeyshaykhullin and @xerenahmed . That seems like a good workaround for now.

**Comment by karolbilicki** [comment] 2021-07-05 11:17
1.05 - the workaround with copied pages doesn't work (prod), dev environment works fine 
1.01 - the workaround with copied pages works, but I get the error related to $RefreshHelpers$' string 😂  when I run `nx start myapp`

any suggestions?

**Comment by shelooks16** [comment] 2021-07-05 12:27
Hi @karolbilicki 

> 1.01 - the workaround with copied pages works, but I get the error related to $RefreshHelpers$' string when I run `nx start myapp` (dev envrionment without building)


this is fixed in 1.0.4 and 1.0.5. Below these versions you won't be able to pair NX and next-translate :(

> 1.05 - the workaround with copied pages doesn't work (prod), dev environment works fine

are you using docker? I have been using the workaround with docker up until now and haven't experienced any problems.

**Comment by karolbilicki** [comment] 2021-07-05 12:31
I am going to use 1.01 in order to use the workaround with coping pages directory for prod.

For development I will upgrade the version to 1.07 but only locally.

**Comment by exsesx** [comment] 2021-08-10 13:44
Any more workarounds?..

**Comment by quyphan97** [comment] 2021-09-15 01:58
![Capture](https://user-images.githubusercontent.com/59947963/133357816-2c09db8d-a45a-4b10-9c76-8c1ce0758102.PNG)
help me error

./pages/blog/[detail].tsx
Module parse failed: Duplicate export '__N_SSP' (11:11)
File was processed with these loaders:
 * ../../node_modules/next/dist/build/babel/loader/index.js
 * ../../node_modules/next-translate/lib/cjs/plugin/loader.js
 * ../../node_modules/next/dist/build/babel/loader/index.js
You may need an additional loader to handle the result of these loaders.
| import { useRouter } from 'next/router';
| export var __N_SSP = true;
> export var __N_SSP = true;
| export function DetailBlogPage() {
|   var route = useRouter();

**Comment by aralroca** [comment] 2021-09-15 11:32
It should be fixed in [1.1.0-canary.3](https://github.com/vinissimus/next-translate/releases/tag/1.1.0-canary.3) version. I close the issue but it would be nice to know your feedback that now it works without problems. If not, I will reopen the issue.

**Closed by aralroca** 2021-09-15 11:32 UTC
Labels: bug, Needs investigation

**Comment by quyphan97** [comment] 2021-09-17 01:31
@aralroca thanks. butt is it will work fine

**Comment by quyphan97** [comment] 2021-09-17 01:52
@aralroca please help me

**Comment by shelooks16** [comment] 2021-09-17 02:17
@quyphan97 try to use function expression for the component and function declaration for getServerSideProps:
```ts
const MyPage = () => { ... }

export async function getServerSideProps() { ... }
```

**Comment by quyphan97** [comment] 2021-09-17 04:59
@shelooks16 Thanks. I will report back to you once the results are available

**Comment by aralroca** [comment] 2021-09-17 10:46
@quyphan97 @amosbastian I've made a fix in the [1.1.0-canary.4](https://github.com/vinissimus/next-translate/releases/tag/1.1.0-canary.4), I hope that with this version it will work.

**Comment by quyphan97** [comment] 2021-09-17 14:27
@aralroca @shelooks16 Thank you, I have fixed the above error. Thanks a lot

**Comment by danyhiol** [comment] 2023-01-28 22:54
Did anyone manage to deploy to [production](https://github.com/aralroca/next-translate/issues/476#issuecomment-1407501531) using `NX-monorepo` or any `monorepo`?
My guess is that `.env.local` is somehow not taken into account or not pointing to the same path when building for prod with `npm run start`. Everything works just fine in dev (when using `npx nx run myapp:serve`). But on prod, I use `npm run start` (> `nx start`) it [fails](https://github.com/aralroca/next-translate/issues/476#issuecomment-1407501531).

**Comment by AlexandreCassagne** [comment] 2023-04-28 15:08
Same issue here @danyhiol. Please let me know if you have resolved this
