### ISSUE TITLE
Use locale not for all pages

### ISSUE THREAD

**Issue by arnaudjnn** [vinissimus/next-translate#313] opened 2020-11-09 09:28 UTC
I only need the locale for a product page => /en-FR/my-product but not for the rest of the app => /en/about.

This setup is possible with next-translate? I don't want to build n * locales pages for each, only for the product one.

**Comment by aralroca** [comment] 2020-11-09 10:21
I think this issue should be directed to the Next.js repository. 

After Next 10 and next-translate 0.19, the whole routing part used in next-translate is now integrated under Next.js. So now next-translate does not take over the routing part anymore.  So I would say that it is something that is not possible to do unless Next.js supports it, so I think it would be better to create the issue there so they can develop it.

Now the responsibility of next-translate is to load the translations on each page, so for the next-translate part you only have to provide the namespace to the page you want. The idea is to remove the "build step" in version 1.0, providing a Next.js plugin: https://github.com/vinissimus/next-translate/issues/303

Hope it helps

**Comment by aralroca** [comment] 2020-11-20 18:56
I close this issue since the whole routing of i18n is now part of Next.js and the issue is supposed to be addressed there

**Closed by aralroca** 2020-11-20 18:56 UTC
