### ISSUE TITLE
All language files are loaded on first request when using SWC

### ISSUE THREAD

**Issue by Parnswir** [vinissimus/next-translate#741] opened 2021-11-29 08:46 UTC
Upgrading a medium-sized project to Nextjs 12, we noticed that switching to SWC from Babel increases our bundle size considerably. One culprit seems to be next-translate.

Before the upgrade, language files have their own chunks and only a small part of the "pages/_app" bundle is used by the library:
![Babel](https://user-images.githubusercontent.com/5978382/143834888-9be27510-14bd-4f2e-b0d2-ed82324e21b5.png)

With SWC (deleted .babelrc), we see all language files included in the app:
![SWC](https://user-images.githubusercontent.com/5978382/143835166-fbfe815c-850b-4256-b25a-404583a905de.png)

Is this a known issue or are we doing something wrong?

We do have a custom fallback in our `i18n.js`:

```js
module.exports = {
  locales: ["en", "de"],
  defaultLocale: "en",
  loadLocaleFrom: async (lang, ns) => {
    const locales = await import(`./locales/${lang}/${ns}.json`).then(
      (m) => m.default
    );
    const defaultLocales =
      lang != "en"
        ? await import(`./locales/en/${ns}.json`).then((m) => m.default)
        : {};
    return { ...defaultLocales, ...locales };
  },
  pages: { ... }
};
```

**Comment by r-ogarkov** [comment] 2022-01-18 13:30
Same issue

**Comment by alisakova** [comment] 2022-01-18 13:31
hi! we have the same issue in our team and our app.js file has been increased from 40kb to 600kb because of this

**Comment by isemog** [comment] 2022-02-28 10:38
Hello, had the same issue, the only way to solve it, was to replace import with fetch

`return fetch(`${baseUrl}/locales/${lang}/${ns}.json`).then((m) => m.json());`

**Comment by vadymshymko** [comment] 2022-04-29 17:38
Hi there! Are there any updates on a possible solution to this issue?

The solution described in @isemog comment does not suit me, as fetch does not allow to make a call with a relative path (I get an error 'only absolute urls are supported')

**Comment by vadymshymko** [comment] 2022-04-29 22:44
Maybe this problem is related to a possible nextcompiler bug, which is described [here](https://github.com/vercel/next.js/issues/33394)?

**Comment by aralroca** [comment] 2022-05-02 07:41
yes it looks related to https://github.com/vercel/next.js/issues/33394

If it is something on the part of next-translate is something that should be investigated because it happens from version 12 of Next.js.

**Comment by vadymshymko** [comment] 2022-05-02 12:00
> yes it looks related to [vercel/next.js#33394](https://github.com/vercel/next.js/issues/33394)
> 
> If it is something on the part of next-translate is something that should be investigated because it happens from version 12 of Next.js.

I just tested the build without using loadLocaleFrom (i.e. using the standard next-translate file structure).  As a result, the size of the bundle did not increase.  Considering this and the fact that next-translate, as far as I understood from studying the source code, also uses dynamic imports in its own loadLocaleFrom implementation, we can argue that the problem is in nextcompiler, and not in next-translate

**Comment by aralroca** [comment] 2022-05-03 08:19
Ok thanks! I close the issue as I see it is reported to the Next.js repository which is where the problem is. https://github.com/vercel/next.js/issues/33394

**Closed by aralroca** 2022-05-03 08:19 UTC
Labels: Needs investigation

**Comment by derkoe** [comment] 2022-06-03 10:48
I have found a solution for that. The code splitting works correctly when the imports are directly in "pages/_app".

Here is an example with complex language fallback logic and "lang-country" locales:

`i18n.js`
```js
module.exports = {
  locales: ["en", "de-AT", "sk-SK"],
  defaultLocale: "en",
  pages: {
    "*": ["my-bundle"],
  },
  loader: false,
  localeDetection: false,
};
```

`pages/app.tsx`
```ts
import "../styles/globals.css";
import type { AppProps } from "next/app";
import appWithI18n from "next-translate/appWithI18n";
import i18nConfig from "../i18n";
import merge from 'lodash/merge';

function MyApp({ Component, pageProps }: AppProps) {
  return <Component {...pageProps} />;
}

export default appWithI18n(MyApp as any, {
  ...i18nConfig,
  loadLocaleFrom: (locale, ns) => {
    const englishTexts = import(`../locales/en/${ns}.json`);
    let countrySpecific = Promise.resolve({});
    let languageOnly = Promise.resolve({});
    if (locale) {
      countrySpecific = import(
        `../locales/${locale.replace("-", "_")}/${ns}.json`
      ).catch(() => ({}));
      languageOnly = import(
        `../locales/${locale.substring(0, 2)}/${ns}.json`
      ).catch(() => ({}));
    }
    return Promise.all([englishTexts, countrySpecific, languageOnly]).then(
      ([en, country, language]) => merge({}, en, country, language)
    );
  },
});
```

**Comment by yfhui** [comment] 2022-11-09 03:41
> I have found a solution for that. The code splitting works correctly when the imports are directly in "pages/_app".
> 
> Here is an example with complex language fallback logic and "lang-country" locales:
> 
> `i18n.js`
> 
> ```js
> module.exports = {
>   locales: ["en", "de-AT", "sk-SK"],
>   defaultLocale: "en",
>   pages: {
>     "*": ["my-bundle"],
>   },
>   loader: false,
>   localeDetection: false,
> };
> ```
> 
> `pages/app.tsx`
> 
> ```ts
> import "../styles/globals.css";
> import type { AppProps } from "next/app";
> import appWithI18n from "next-translate/appWithI18n";
> import i18nConfig from "../i18n";
> import merge from 'lodash/merge';
> 
> function MyApp({ Component, pageProps }: AppProps) {
>   return <Component {...pageProps} />;
> }
> 
> export default appWithI18n(MyApp as any, {
>   ...i18nConfig,
>   loadLocaleFrom: (locale, ns) => {
>     const englishTexts = import(`../locales/en/${ns}.json`);
>     let countrySpecific = Promise.resolve({});
>     let languageOnly = Promise.resolve({});
>     if (locale) {
>       countrySpecific = import(
>         `../locales/${locale.replace("-", "_")}/${ns}.json`
>       ).catch(() => ({}));
>       languageOnly = import(
>         `../locales/${locale.substring(0, 2)}/${ns}.json`
>       ).catch(() => ({}));
>     }
>     return Promise.all([englishTexts, countrySpecific, languageOnly]).then(
>       ([en, country, language]) => merge({}, en, country, language)
>     );
>   },
> });
> ```

This solution works! nice workaround for the problem. But I am hoping for an offical fix for it

**Comment by stefnnn** [comment] 2022-11-09 08:42
Can confirm, that @yfhui's workaround does indeed work without increasing the bundle size.
