### ISSUE TITLE
External anchor links broken in version 1.3.2

### ISSUE THREAD

**Issue by mhwinkler** [vinissimus/next-translate#769] opened 2022-01-25 01:02 UTC
#768 introduced a [change to how templates are parsed](https://github.com/vinissimus/next-translate/pull/768/files#diff-f3dac136b11842d0bdf3ba5dba291a9e264358361f747a711bfbed07d765a86cR17-R20) which appears to be an attempt to strip comments from the template file before processing it. I believe there is an issue with this approach (or the underlying RegExp processing), because it blows up for me on any normal external link in my Page template, e.g.:
```jsx
<a href="https://www.google.com">This should link to Google</a>
```

The presence of any external URL will cause the build to fail (probably along with any other valid usage of `//` in the JSX). 

In my case, this bug manifests with a confusing `"Unexpected token ``div``. Expected jsx identifier"` error at runtime.

Here's a simple [code sandbox](https://codesandbox.io/s/next-translate-bug-v1-3-2-ieo95) where you can experience the issue firsthand by uncommenting the link found in `pages/index.js:19-21`.

Reverting to v1.3.0 or before fixes the issue. 

Thank you for the hard work on this fantastic plugin! 🎉

**Comment by cccmf** [comment] 2022-01-25 10:14
1.3.2 breaks my application as well. I get the following errors:

`./pages/accessibility.tsx
Error: error: Unexpected token `div`. Expected jsx identifier
  
   |
37 |       <div>
   |        ^^^

Caused by:
    0: failed to process js file
    1: Syntax Error

./pages/index.tsx
Error: error: Unexpected token `HomepageLayout`. Expected jsx identifier
  
   |
34 |     <HomepageLayout>
   |      ^^^^^^^^^^^^^^

Caused by:
    0: failed to process js file
    1: Syntax Error`


1.3.0 breaks if I insert jsondlt into the next's header component:

`jsonDlt = {
    '@context': 'http://schema.org', // <- this breaks
    '@type': 'ItemList', // <- this breaks
    name: ...
    numberOfItems: ...,
    itemListElement: items.map((item: IItem, index: number) => ({
      '@type': 'ListItem', // <- this breaks
      position: index + 1,
      item: generateJsonDlt(item, locale),
    })),
    itemListOrder: 'https://schema.org/ItemListOrderAscending', // <- this breaks
    url: (process.env.NEXT_PUBLIC_FONT_END_URL as string) + req.url,
  };`

Injecting it in the header like that:

`<Head>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
            __html: jsonDlt,
        }}
    />
</Head>`

Everything used to work in 1.2.0.

**Comment by aralroca** [comment] 2022-01-25 19:17
Ok, I'm going to revert the last commit and solve it with a different approach. Thanks to report it

**Comment by aralroca** [comment] 2022-01-25 19:21
https://github.com/vinissimus/next-translate/commit/bbaa3bfa3ba8c2fcd3b61f6a54fb6ffa0843d3fc

**Comment by aralroca** [comment] 2022-01-25 19:22
1.3.3 released without the last commit. I'm going to reopen the issue to fix it with a different approach.

**Closed by aralroca** 2022-01-25 19:22 UTC
