### ISSUE TITLE
Next-translate not working on IE

### ISSUE THREAD

**Issue by DimaSmakouz** [vinissimus/next-translate#435] opened 2021-01-07 15:05 UTC
Hello. I'm trying to run example from [https://github.com/vercel/next.js/tree/master/examples/with-next-translate](https://github.com/vercel/next.js/tree/master/examples/with-next-translate) on IE 11, and it seems broken. 

![image](https://user-images.githubusercontent.com/71767624/103905266-1098c380-5107-11eb-8978-72e39a88e866.png)
The same behavior occurs with all examples from this repo.
When i remove next-translate from **next.config.js**, everything works fine. 
Any suggestions about what type of problem it can be?
- **OS:** Windows 10 (64-bit)
- **Node:** 14.2.0
- **Browser:** Internet Explorer 11

**Comment by aralroca** [comment] 2021-01-07 21:20
@DimaSmakouz maybe you need to add a polyfill for pluralrules https://caniuse.com/intl-pluralrules

**Comment by stpch** [comment] 2021-01-07 23:14
I've been hunting this bug down for a while now and also isolated it to `next-translate`. After making sure to have all necessary polyfills and transpiling npm packages without ES5 code, the following errors remain:

In **dev mode**:

```
Warning: Did not expect server HTML to contain a <div> in <div>.

The above error occurred in the <I18nProvider> component:

   at I18nProvider (http://localhost:3000/_next/static/chunks/pages/_app.js?ts=1610060100278:244230:5)
   at AppWithTranslations (http://localhost:3000/_next/static/chunks/pages/_app.js?ts=1610060100278:244399:5)
   at construct (http://localhost:3000/_next/static/chunks/polyfills.js?ts=1610060100278:11:29680)
   at ReactDevOverlay (http://localhost:3000/_next/static/chunks/main.js?ts=1610060100278:885:5)
   at construct (http://localhost:3000/_next/static/chunks/polyfills.js?ts=1610060100278:11:29680)
   at AppContainer (http://localhost:3000/_next/static/chunks/main.js?ts=1610060100278:9912:3)
   at Root (http://localhost:3000/_next/static/chunks/main.js?ts=1610060100278:10041:3)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```

The first `<div>` seems to refer to the outermost element of the page component. Changing it for example to a `<h1>` changes this error message accordingly. 

In the **production build**:

![image](https://user-images.githubusercontent.com/1090696/103954877-68eeb600-5145-11eb-8cd8-f959b6cef520.png)

The console fills up really fast with these and then the browser becomes unresponsive or crashes.

Removing the `next-translate()` wrapper in `next.config.js` also makes these issues go away for me.

**Comment by aralroca** [comment] 2021-01-11 09:14
@stpch are you adding this polyfills on webpack configuration inside `next.config.js` or how?

https://github.com/zeit/next.js/blob/canary/examples/with-polyfills/next.config.js

It would be great to know the steps to reproduce it. Thank you!

**Comment by DimaSmakouz** [comment] 2021-01-11 21:43
@aralroca Thank you. Appreciate your support!
I found solution that's work in IE (at least 11) in dev and build mode.

Just import the bunch of polyfills on top of your custom _app.js. No need for webpack tweaking in next.config.js.
I get this polyfills from [https://formatjs.io/docs/polyfills/intl-pluralrules/](https://formatjs.io/docs/polyfills/intl-pluralrules/)

For example, to support en and ru locales, i import this polyfills on top of _app.js in this order:

```
import '@formatjs/intl-getcanonicallocales/polyfill';
import '@formatjs/intl-locale/polyfill';
import '@formatjs/intl-pluralrules/polyfill'
import '@formatjs/intl-pluralrules/locale-data/en'
import '@formatjs/intl-pluralrules/locale-data/ca'
```

**Comment by aralroca** [comment] 2021-01-14 20:09
@DimaSmakouz  I'm glad it works for you. Then I close the issue since the solution for IE is to use polyfills. Also thanks for reporting the issue, anything else don't hesitate to create another issue! Thank you very much!

**Closed by aralroca** 2021-01-14 20:09 UTC

**Comment by lipoolock** [comment] 2021-01-15 10:45
Just to add a bit more support on that topic (and thank you for pasting the list of polyfills you used @DimaSmakouz, because I was missing some of them to make it work properly), below a link to a codesandbox with that fix implementation
https://codesandbox.io/s/aged-hooks-plbmu

**Comment by stpch** [comment] 2021-01-16 01:21
@DimaSmakouz thank you, that did the trick! I was actually missing one of those polyfills. Would be great to add this to the readme.
