### ISSUE TITLE
Have translated urls for different languanges of the same page ( route )

### ISSUE THREAD

**Issue by hitaboy** [vinissimus/next-translate#227] opened 2020-07-15 11:23 UTC
I cannot find a way to have translated urls of a route. 
Like: 
/about
/es/acerca-de-nosotros
/ca/sobre-nosaltres
and all cases be the same about route.
Is it possible?

**Comment by aralroca** [comment] 2020-07-15 12:53
@hitaboy this is not supported right now in this library. But maybe you can fix this using the **rewrites** feature of next.js:

* https://github.com/vercel/next.js/discussions/9081#discussion-5567

I'm going to close it because is a duplicate of https://github.com/vinissimus/next-translate/issues/154

**Closed by aralroca** 2020-07-15 12:53 UTC
