### ISSUE TITLE
How can I use the translation in the _document.tsx? (I'm using the custom server for SSR)

### ISSUE THREAD

**Issue by wilsonneto-dev** [vinissimus/next-translate#249] opened 2020-09-04 14:20 UTC
Hi guys,
How can I use the translation in the _document.tsx? I would like use the translation in the meta tags and open graph tags like description and title tags.

Thanks so much!

**Comment by aralroca** [comment] 2020-09-11 19:36
Internals pages as `_app.js` and `_document.js` are not involved with translations for now. There is an open issue for this: https://github.com/vinissimus/next-translate/issues/44

Maybe [documentLang](https://github.com/vinissimus/next-translate#documentlang) can help you, and depending on the language load one locale or another. The problem is that you need to import the JSONs for all the languages, but you can use a small JSON for just the `_document.js`. Something like:

```js
import Document, { Html, Head, Main, NextScript } from 'next/document'
import documentLang from 'next-translate/documentLang'
import useTranslation from 'next-translate/useTranslation'
import I18nProvider from 'next-translate/I18nProvider'

import metainfoES from '../../locales/es/metainfo.json'
import metainfoEN from '../../locales/en/metainfo.json'

const namespaces = {
   es: metainfoES,
   en: metainfoEN,
}

export default class MyDocument extends Document {
  render() {
    const lang = documentLang(this.props)

    return (
      <Html lang={lang}>
        <I18nProvider lang={lang} namespaces={{ metainfo: namespaces[lang] }}>
           <CustomHead />
        </I18nProvider>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}

function CustomHead() {
  const { t } = useTranslation()
  const title = t`metainfo:title`
  const description = t`metainfo:description`

   return (
       <Head>
          <title>{title}</title>
          <meta name="description" content={description} />
      </Head>
  )
}
```

**Comment by wilsonneto-dev** [comment] 2020-09-13 17:53
Thanks so much!

**Comment by aralroca** [comment] 2020-09-14 06:41
Cool, if this solves your problems, I'll close the issue, as there is already another one to better address the issue of translations in internal pages of next.js such as `_app.js` and `_document.js`.

**Closed by aralroca** 2020-09-14 06:41 UTC

**Comment by nathanguillaumin** [comment] 2021-02-25 11:37
Hello @aralroca, I am having the same issue. I would like to use and update the language in _document.tsx for HTML as soon as the user choose a new language. 
I have trying using the documentLang and the cookies but don't thinks it's optimal. What is your idea for this?
Thanks a lot

**Comment by aralroca** [comment] 2021-02-25 12:08
@nathanguillaumin During the i18n routing the HTML lang is automatically handled.

**Comment by nathanguillaumin** [comment] 2021-02-25 12:21
@aralroca Thanks. How would you make it?

I am trying getting the `lang` with `const { lang } = this.props.i18n;` and then englobing my export as:
`export default withTranslation(Document);`

But get an error: `TypeError: Document.renderDocument is not a function`

Thanks a lot for your help

**Comment by aralroca** [comment] 2021-02-25 16:57
I meant that there is no need to do the `<Html lang={documentLang()}>` because the lang is already automatically placed inside the HTML tag.
