### ISSUE TITLE
Translations are not loading during client-side navigation

### ISSUE THREAD

**Issue by vaniyokk** [vinissimus/next-translate#558] opened 2021-03-31 08:37 UTC
Hi! Unfortunately translations are not loading during client-side navigation in latest version.

I have latest Next.js **v10.1.0** and next-translate **v1.0.5**

My page is wrapped in a HOC that adding page metadata and not using any data-fetching methods.

```
import { NextPage } from "next";

import Discover from "~/components/Discover";
import withStandardMetadata from "~/components/providers/withStandardMetadata";

const DiscoverPage: NextPage = (): JSX.Element => <Discover />;

export default withStandardMetadata({
  titleKey: "discover_title",
  descriptionKey: "discover_description",
  keywordsKey: "discover_keywords"
})(DiscoverPage);
```

If I downgrade next-translate to **1.0.1** translations are loading fine on both server-side and client-side navigation.
I checked every version prior to 1.0.5 and all versions have same problem.

adding of empty **getStaticProps** to my page like this
```
export const getStaticProps: GetStaticProps<
  Record<string, unknown>
> = async () => ({ props: {} });

```
fixes the problem but I don't want to bloat all my pages with such dummy code.

Is there any other way to get around with this?
It looks like a regression from **v1.0.1**. Do you more information to investigate the problem?

**Comment by picardplaisimond** [comment] 2021-04-02 04:08
Someone have a solution for this ? This is a new problem for me too.
I'm just using a normal HOC without any extra fetching.
I think it's a false alert from "next-translate". I'm also getting: 

`🚨 [next-translate] In Next 10.x.x there is an issue related to i18n and getInitialProps. We recommend to replace getInitialProps to getServerSideProps on /index.js. Issue: https://github.com/vercel/next.js/issues/18396`

**Comment by aralroca** [comment] 2021-04-06 09:09
@picardplaisimond this issue will be fixed after this PR will be merged: https://github.com/vercel/next.js/pull/21930

@vaniyokk using HOC is using `getInitialProps` as default to avoid conflicts with HOC, and `getInitialProps` has this issue that will be fixed after this PR merged  https://github.com/vercel/next.js/pull/21930. However, to force to load the translations in a different loader you should define another loader (as you comment, and empty `getStaticProps` solves). For now is the only way.

I am closing the issue as it is a duplicate of this one: https://github.com/vinissimus/next-translate/issues/453

**Closed by aralroca** 2021-04-06 09:09 UTC
