### ISSUE TITLE
Deployement error Using next translate

### ISSUE THREAD

**Issue by Leonardll** [vinissimus/next-translate#876] opened 2022-07-05 14:51 UTC
Hi there, I am having issues when I try to deploy my app using next translate.  Error message is related to an array of data fetched from locales files. It work perfectly in on localhost but when I am trying to deploy it. Getting map is not function. 

Does anyone have clue of how it can be fixed?
Should i use getstaticprop on the page to fix this?

```js
import Image from "next/image";
import { AiOutlinePlus, AiOutlineMinus } from "react-icons/ai";
import { useState, useEffect } from "react";
import useTranslation from "next-translate/useTranslation";
import { Contact } from "../../components/contact/Contact";

const Conciergerie = () => {
  let { t, i18n, ready } = useTranslation("conciergerie", {
    useSuspense: true,
  });

  const scrollToConciergerie = () => {
    window.scrollTo({
      top: 300,
      behavior: "smooth",
    });
  };

  const myLoader = ({ src, width, quality }) => {
    return `${src}?w=${width}&q=${quality || 75}`;
  };

  const [showform, setshowform] = useState(false);

  useEffect(() => {
    window.addEventListener("load", scrollToConciergerie);
    return () => {
      window.removeEventListener("load", scrollToConciergerie);
    };
  });

  const showContactForm = () => {
    return <Contact />;
  };

  const contentData = t(
    "conciergerieData",
    { count: 1 },
    {
      returnObjects: true,
    }
  );

  return (
    <div className="section" onLoad={scrollToConciergerie}>
      <div className="container">
        <div className="text-center">
          <h1 className=" my-4 text-capitalize" id="conciergerie">
            {t("conciergerieHeader")}
          </h1>
        </div>
        <h3 className="text-capitalize concierge-subheading mt-3">
          {t("conciergerieTitle")}
        </h3>
        <p className="lead concierge-subheading-text">
          {t("conciergerieText")}
        </p>
      </div>
      <div className="container">
        <div className="row text-center mt-5">
          {contentData?.map((item) => {
            return (
              <div className="col-md-4" key={item.id}>
                <span className="fa-stack fa-4x">
                  <Image
                    layout="fill"
                    src={item.icon}
                    alt=""
                    className="svg-inline--fa fa-solid  fa-stack-1x fa-inverse"
                    aria-hidden="true"
                    focusable="false"
                    data-prefix="fas"
                    data-icon="house"
                    role="img"
                    loader={myLoader}
                  />
                </span>
                <h4 className="my-3 text-hogar2 text-uppercase">
                  {item.title}
                </h4>
                <ul>
                  {item.text.map((text) => {
                    return (
                      <li key={text.id} className="list-unstyled">
                        <p className="m-0 text-muted text-list">
                          {text.content}
                        </p>
                      </li>
                    );
                  })}
                </ul>

                {item.id === "algomas" &&
                  (!showform ? (
                    <AiOutlinePlus
                      role="button"
                      onClick={() => {
                        setshowform(!showform);
                      }}
                      className="fs-2"
                      fill="#5ab4ab"
                    />
                  ) : (
                    <AiOutlineMinus
                      role="button"
                      onClick={() => {
                        setshowform(!showform);
                      }}
                      className="fs-2"
                      fill="#5ab4ab"
                    />
                  ))}
                {item.id === "else" &&
                  (!showform ? (
                    <AiOutlinePlus
                      role="button"
                      onClick={() => {
                        setshowform(!showform);
                      }}
                      className="fs-2"
                      fill="#5ab4ab"
                    />
                  ) : (
                    <AiOutlineMinus
                      role="button"
                      onClick={() => {
                        setshowform(!showform);
                      }}
                      className="fs-2"
                      fill="#5ab4ab"
                    />
                  ))}
              </div>
            );
          })}
        </div>
        {showform && showContactForm()}
      </div>
    </div>
  );
};

export default Conciergerie;
```

![image](https://user-images.githubusercontent.com/33690476/177396033-20679d4d-0d62-4547-b717-576fe11bf66b.png)

**Comment by Leonardll** [comment] 2022-07-06 11:02
Hi Aralroca, thanks for answering. I am not using next export in my script.  the repo is public on my profile.  It's name is unicohogar. 😊

**Comment by aralroca** [comment] 2022-07-06 11:48
I have seen that you don't have a `next.config.js` with `nextTranslate` webpack loader, you should add it with:

```js
const nextTranslate = require('next-translate')

module.exports = nextTranslate()
```

Then, I see an error with your images (nothing to do with next-translate).

![image](https://user-images.githubusercontent.com/13313058/177543143-9a2f253a-38a5-4019-88ab-0b6b473c620c.png)


After removing the images, doing `yarn build && yarn start` works correctly.

![image](https://user-images.githubusercontent.com/13313058/177543223-315329ee-69ed-4275-ada0-623eb2604901.png)

**Comment by Leonardll** [comment] 2022-07-06 12:04
thanks for looking at this. I am having a different error message on vercel log interfaces. i will have a look at this. next config is the git ignore so not pushed on the github repo. Please see below `const path = require("path");
const nextTranslate = require("next-translate");
const { i18n } = require("./next-i18next.config");
module.exports = {
  //...nextTranslate(),
  i18n: {
    //   // These are all the locales you want to support in
    //   // your application
    locales: ["es-ES", "en-US"],
    //   // This is the default locale you want to be used when visiting
    //   // a non-locale prefixed path e.g. `/hello`
    defaultLocale: "es-ES",
    trailingSlash: true,
  },
  reactStrictMode: true,
  sassOptions: {
    includePaths: [path.join(__dirname, "styles")],
  },
  images: {
    formats: ["image/avif", "image/webp"],
    deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
    domains: [
      "realestate-eosin-xi.vercel.app",
      "img3.idealista.com",
      "unicohogar.com",
    ],
  },

  module: {
    rules: [
      //...
      {
        test: /\.(png|jp(e*)g|svg|gif)$/,
        use: [
          {
            //loader: ['file-loader'],
            options: {
              name: "images/[hash]-[name].[ext]",
            },
          },
        ],
      },
    ],
  },
};
`

**Comment by Leonardll** [comment] 2022-07-06 12:48
Thanks a million. i am using npm not yarn. I am going to try to deploy it see what it says. I will let you know
One more thing, it is good you have mentioned picture issues, because i am having issues with   images src path stored in my locales files , i am getting error 404 when i load the page. Think it is related to next-translate?

**Comment by aralroca** [comment] 2022-07-06 12:52
It doesn't look like it's from next-translate. without next.config.js I got the same error (without next-translate touching Webpack), and it works correctly with next-translate for me after removing the images. 

If so, I close the issue. If you continue investigating and see that it is a problem of next-translate you comment it here and we will reopen the issue. But if it is not a problem of this library there is little we can do to solve it.

**Comment by aralroca** [comment] 2022-07-06 13:43
Would you add a `console.log` to see the `lang` before the Vercel error?

```js
const RealEstate = () => {
  let { t, lang } = useTranslation("realEstate", { useSuspense: true });
  console.log({ lang }) // Add a console.log to see the lang before Vercel error
  const contentData = t("propertyData", { count: 1 }, { returnObjects: true });
```

I don't know the process of Vercel how it makes the prerendered pages but if there is an error it could be that the locale is different from yours? At least we know if the problem is with the locale or loading the file with the correct locale. Thank you!

**Comment by Leonardll** [comment] 2022-07-06 13:52
that's a great to see the error. I have done it and it highlights that on localhost contentData is an object but when it comes to put in production it is a string. See screenshots below, please
![image](https://user-images.githubusercontent.com/33690476/177566211-bd34fbe0-bc28-45ca-ac17-071c4014658a.png)

<img width="974" alt="image" src="https://user-images.githubusercontent.com/33690476/177566314-287d8aeb-53b7-48bd-9ef2-81e4d88d1e81.png">

**Comment by aralroca** [comment] 2022-07-06 16:07
Ok! Just one more test:

add `useRouter` from Next.js:

```js
import { useRouter } from 'next/router'
```

And check if locale is also an empty string (like `lang`). Or if is an error of next-translate that the `lang` is different than the `locale` from Next.js:

```js
let { locale } = useRouter()
let { t, lang } = useTranslation("realEstate");
console.log({ lang, locale })
```

Thank you so much!!

- If `lang === locale` (both are an empty string): Nothing to do, is something related with Vercel.
- If `lang !== locale`. Looks like a bug of next-tranlate that we need to fix.

**Comment by Leonardll** [comment] 2022-07-06 16:19
you are very welcome, i am happy if i can help. :) 
i did as you said and it seems that lang === locale on localhost but on vercel interface log i get lang empty string and locale is undefined. Please see screenshot below 
![image](https://user-images.githubusercontent.com/33690476/177597220-55cabd9b-8ecc-45da-85f8-80f78d382d00.png)
<img width="947" alt="image" src="https://user-images.githubusercontent.com/33690476/177597320-28ebb577-b884-4b16-9e16-10241fd46f8f.png">

**Comment by aralroca** [comment] 2022-07-07 10:11
@Leonardll If the `locale` is `undefined`, the behavior of `lang `being an empty string is correct. With this, I see that it is not a bug of `next-translate`, it is how Vercel prerenders the pages, that at some point do not have the `locale` defined.

The [`default`](https://github.com/vinissimus/next-translate#usetranslation) field I mentioned before should work correctly in the new version of next-translate [1.5.0](https://github.com/vinissimus/next-translate/releases/tag/1.5.0). Can you confirm this?

I close the issue. If the default property doesn't work for something, let me know and I'll reopen it and we'll see what happens.

Thank you

**Closed by aralroca** 2022-07-07 10:11 UTC

**Comment by Leonardll** [comment] 2022-07-07 10:16
thanks for your @aralroca . I really appreciate. 
I have used the default as follow : 
`const contentData = t(
    "conciergerieData",
    { count: 1 },
    {
      returnObjects: true,
      default: [],
    }
  );`
i will raise and issue with next js then and see if they can fix it .

Many thanks again :)

**Comment by Leonardll** [comment] 2022-07-08 09:36
Hi @aralroca  i have tried with the latest version of next-translate nothing works. Same error. It works all good on localhost but it breaks in built time. It is a shame because next-translate is the less complex to implement among the others. i will have to pick another one, my client cannot wait any longer.

**Comment by aralroca** [comment] 2022-07-08 09:44
What is the error?  Is `contentData` an empty array `[]`? Although with Vercel the locale is `undefined`, you should have an empty array if you use the `default: []` property, and you should no longer get a code crash. Or it crashes for another reason? Thank you.

**Comment by Leonardll** [comment] 2022-07-08 09:54
well i wish my friend, lang is an empty string and locale is undefined. Typeof contentData is string where on localhost it returns what we want , i have already provided the screenshot. It is the same error.

**Comment by Leonardll** [comment] 2022-07-08 14:32
@aralroca what do you think i should do now?

**Comment by Leonardll** [comment] 2022-07-11 09:57
Hi @aralroca , have you found any further information on this issue, please.
?
